name: popup_menu_2_example
description: An example of long press popup.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: '>=2.18.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    popup_menu_2:
        path: ../
    get: ^4.7.3
    console_tools: ^2.0.4
    flutter_launcher_icons: ^0.14.4
    flutter_native_splash: ^2.4.7

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
