name: popup_menu_2
description: A popup menu containing clickable buttons, each with a global click function referring to the item. This is designed to avoid breaking the user's attention.
repository: https://github.com/ymrabti/popup_menu_2.git
homepage: https://popup-menu-2-demo.youmti.net/
documentation: https://popup-menu-2-docs.youmti.net/
topics:
    - flutter
    - popup-menu
    - context-menu
    - bubble-menu
    - no-attention-break

version: 0.1.6

environment:
    sdk: '>=2.18.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
